version: '3.7'

services:
  web:
    image: nginx:latest
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./docker/nginx/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    depends_on:
      - php
      - mongo
    networks:
      - server

  php:
    build:
      dockerfile: ./docker/php/Dockerfile
      context: ./
    volumes:
      - ./:/opt
      - composer:/opt/vendor
    networks:
      - server
      - database

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    volumes:
      - mongo-data:/data/db
#      - ./docker/database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - 27017:27017
    networks:
      - database

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      # Has to be root or fails
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
    networks:
      - database

volumes:
  mongo-data:
  composer:

networks:
  server:
  database:
