version: '3.7'

services:

  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./src:/opt
      - ./site.conf:/etc/nginx/conf.d/default.conf
      - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    networks:
      - server
    depends_on:
      - php
      - mongo

  php:
    image: php:7-fpm
    volumes:
      - ./src:/opt
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - server
      - database

  mongo:
    image: mongo
    volumes:
      - mongo-data:/opt/data/db
      - ./database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=users
    networks:
      - database

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
    depends_on:
      - mongo
    networks:
      - database

volumes:
  mongo-data:

networks:
  server:
    database:

