version: '3.7'

services:
  web:
    image: nginx:latest
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./:/opt
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./docker/nginx/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    depends_on:
      - php
      - mongo
    networks:
      - server

  php:
    build:
      dockerfile: ./docker/php/Dockerfile
      context: ./
    volumes:
      - ./:/opt
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - server
      - database

  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - mongo-data:/data/db
#      - ./docker/database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: secret
    # Don't think this is needed
    #    ports:
    #      - "27017:27017"
    restart: always
    networks:
      - database

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: test
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
    networks:
      - database

volumes:
  mongo-data:

networks:
  server:
  database:
