<?php

namespace CycleSaver\Infrastructure;

use PHPUnit\Framework\TestCase;

class UserRepositoryIntegrationTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    
}
