version: 2.1
jobs:
  build:
    docker:
      image: circleci/php:7.4.7-cli
    working_directory: ~/back-to-win-api

    steps:
      - run:
          name: Install Docker client
          command: apk add docker-cli      - setup_remote_docker

      - run: echo "hello precheckout"
      - checkout
      - run: ech "after checkout"
          -
      - run:
          name: Build Test Image
          command: docker-compose -f docker-compose.yml up -d --build

      - run:
          name: Test Release Image
          command: bin/docker-test

      - deploy:
          name: Deploy to Production
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              chmod +x ./.circleci/staging/docker-push.sh
              ./.circleci/staging/docker-push.sh
              chmod +x ./.circleci/staging/docker-deploy.sh
              ./.circleci/staging/docker-deploy.sh
            fi
