version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.4.7-cli

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Install Docker client
          command: |
            sudo apt-get update
            apt-get install \
                apt-transport-https \
                ca-certificates \
                curl \
                gnupg-agent \
                software-properties-common
            sudo apt-get install docker-ce docker-ce-cli containerd.io

      - run:
          name: Build test image
          command: docker-compose -f docker-compose.yml up -d --build

      - run:
          name: Test image
          command: bin/docker-test

      - deploy:
          name: Deploy to Production
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              chmod +x ./.circleci/staging/docker-push.sh
              ./.circleci/staging/docker-push.sh
              chmod +x ./.circleci/staging/docker-deploy.sh
              ./.circleci/staging/docker-deploy.sh
            fi
